### ISSUE TITLE
[Bug] Node @utam/compiler v3.2.2 - using chain generates invalid JS - await _statement-1.getTitleElem

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce/utam-java#227]
I'm using it on a personal project and the below config gives me:

```
Error [RollupError]: entry (55:30): Identifier cannot follow number (Note that you need plugins to import files that are not JavaScript)
    at Object.getRollupError (./node_modules/rollup/dist/shared/parseAst.js:285:41)
    ... 4 lines matching cause stack trace ...
    at async ModuleLoader.addModuleSource (./node_modules/rollup/dist/shared/rollup.js:21036:13) {
  cause: Error [RollupError]: Identifier cannot follow number
      at Object.getRollupError (.node_modules/rollup/dist/shared/parseAst.js:285:41)
      at ParseError.initialise (./node_modules/rollup/dist/shared/rollup.js:14824:40)
      at convertNode (./node_modules/rollup/dist/shared/rollup.js:16535:10)
      at convertProgram (./node_modules/rollup/dist/shared/rollup.js:15778:12)
      at Module.setSource (./node_modules/rollup/dist/shared/rollup.js:17514:24)
      at async ModuleLoader.addModuleSource (./node_modules/rollup/dist/shared/rollup.js:21036:13) {
    code: 'PARSE_ERROR',
    pos: 1954
  },
  code: 'PARSE_ERROR',
  id: 'entry',
  pos: 1954,
  loc: { column: 30, file: 'entry', line: 55 },
  frame: '53:     async getTitle() {\n' +
    '54:         // number\n' +
    '55:         await _statement-1.getTitleElem(1);\n' +
    '                                  ^\n' +
    '56:         const _result1 = await this.getText();\n' +
    '57:         return _result1;',
  [Symbol(augmented)]: true
}
```

### Actual behavior
Create a utam file in the root of the project called `test.utam.json` with:

```
{
    "root": true,
    "selector": {
        "css": "#globalWrapper"
    },
    "elements": [{
            "name": "titleElem",
            "public": false,
            "selector": {
                "css": ".mpSectionTitle:nth-of-type(%d)",
                "args": [
                    {
                        "name": "titleIndex",
                        "type": "number"
                    }
                ]
            }
        }
    ],
    "methods": [{
        "name": "getTitle",
        "compose": [
            {
                
                "apply": "getTitleElem",
                "args": [
                    {
                        "value": 1
                    }
                ],
                "chain": true
            },{
                "returnType": "string",
                "apply": "getText"
            }
        ]
    }]
}
```

utam.config.js is:

```
{
    "pageObjectsRootDir": "./",
    "pageObjectsFileMask": ["*.utam.json"],
    "extensionsFileMask": ["*.utam.js"],
    "pageObjectsOutputDir": "pageobjects",
    "alias": {}
}
```

My package.json is:

```
{
    "name": "matt-test",
    "private": true,
    "scripts": {
        "build:utam": "utam -c utam.config.json"
    },
    "devDependencies": {
        "utam": "^3.2.2"
    },
    "engines": {
        "node": ">= 18.20.0"
    },
    "packageManager": "npm@10.7.0"
}
```

- [ ] Unable to compile a Page Object

- [X] Invalid generated code

- [ ] Runtime error

### What is your expected behavior?
Should compile and output:

```
async getTitle() {
         await _statement0.getTitleElem(1);
```

### Steps to reproduce
With the above files just run:

```
npm run build:utam
```

and it will fail

Looks like in:

`@utam/compiler/build/codegen/helpers/statements-body-generator.js`

It has:

```
function generateChainStatement(classContext, statement, statementContext, argsContext) {
    const { applyFunction, applyFunctionArgs = [], matcher, invocationType, returnType } = statement;
    const { index, isPreviousStatementList, isLastStatement, methodName } = statementContext;
    const calleeName = `_statement${index - 1}`;
```

It shouldn't do `- 1` because `index` in the `statementContext` starts at `0`. Hence you get `-1` and hence the compile error message.

### Environment

- UTAM: [e.g 1.0.0] v3.2.2
- Node 18.20.4

### Additional context
Not sure where to report errors for the JS compiler, this is the only github repo I could find that might be suitable.

**Comment by mattgoldspink** [comment]
My bad - looks like I used chain in the wrong place 🤦‍♂️ Would be nice if the compiler could warn about it being used on the first element in the compose chain
